API_KEY: "ENTER-TOMORROW-API-KEY-HERE"
SERVER: "LAPTOP-2NSE0JH1\\SQLEXPRESS"
DATABASE: "dummy"

RESTART_SCRIPT: "src/restartDB.sql"

WEATHER_PATH: "data/weather/tomorrow.csv"
WEATHER_HISTORICAL_PATH: "data/weather/weather_historical.csv"
WEATHER_TABLE: "Weather"

PROJECT_COUNT: 30
PROJECT_START_DATE: "2018-01-01"

DATA_DIR: "data"

SIMULATION_SOURCE: "csv"